version: '3.8'

services:
  web:
    build: .
    container_name: web-dt
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules # Tránh ghi đè thư mục node_modules trong container
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    command: npm start # chạy lệnh nodemon index.js

  redis:
    image: redis:7.2
    container_name: redis-local
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
